name: build-translations
run-name: ${{ github.actor }} is building translations
on: [push]
jobs:
  build-translations:
    runs-on: ubuntu-latest
    steps:
      - uses: ConorMacBride/install-package@v1
        with:
          apt: qttools5-dev-tools

      - name: Build translations
        working-directory: ValeLS/ts
        run: lrelease *.ts